### ISSUE TITLE
Cannot run app

### ISSUE THREAD

**Issue by IgorGanapolsky** [AdamSHurwitz/Coinverse#2]
Get an error: 
> File google-services.json is missing. The Google Services Plugin cannot function without it.

**Comment by adam-hurwitz** [comment]
Hi @IgorGanapolsky, Thank you for downloading the repo! 

You will need the _google-services.json_ file in order to run the project. Please take a look at _[Coinverse Open App — Setup](https://medium.com/coinverse/coinverse-open-app-set-up-7a9fdbd1ba46)_ which outlines the step-by-step process.
